### ISSUE TITLE
What is .pkl format? What all it contains?

### ISSUE THREAD

**Issue by Ankitjaiswal1201** [intelligent-control-lab/Kinect_Smoothing#2]
Hi,
I have depth images in .bmp format.

Is that I have to convert my images to .pkl format? or is there any way to use the images directly?

**Comment by Walleclipse** [comment]
Hi,
We saved  frames of depth images in `data/sample_img.pkl` and saved frames of position coordinates in `data/sample_pose.pkl `
`sample_img.pkl` is a list of image frames .
`e.g.  sample_img <- [ [ image_1 ] ,  [ image_2 ], ... , [ image_t ] ].` 
each `image_i` has a shape of `(width, height)`
Please see detailed information in [example.ipynb](https://github.com/intelligent-control-lab/Kinect_Smoothing/blob/master/example.ipynb)

You can use images directly in any format, but you need to stack them to create a list of image frames. For example:
```
import joblib 
import matplotlib.pyplot as plt  
img1 =  plt.imread('image1.bmp')  
img2 =  plt.imread('image2.bmp')  
img_frames = [[img1], [img2]]   
joblib.dump(img_frames, 'image_frames.pkl')  
```

**Comment by Ankitjaiswal1201** [comment]
Hi,

Thank you for the prompt reply. This worked. 
In case if anyone wants to use it for multiple files, then the code below should work.
```
import joblib 
import cv2
import glob 

X_data = []
file_lists = glob.glob("/home/ankit/Home_Cloud/Proband/Proband20/Fg_depth/*.bmp")
for files in sorted(file_lists):
    if files.endswith(".bmp"):
        image = cv2.imread(files)
        X_data.append(image)
        joblib.dump(X_data, 'image_frames.pkl')

```

**Comment by Cartucho** [comment]
It would be nice to add this info to the readme file.
