### ISSUE TITLE
Running speed

### ISSUE THREAD

**Issue by ruinianxu** [intelligent-control-lab/Kinect_Smoothing#4]
Hi,

I am currently using this approach for real-time Kinect camera depth image smoothing. I collected 45 frames and send them into smoothing algorithm and then the algorithm got stuck at there forever. I changed to use just 2 frames but it didn't help at all. I wonder if I made any mistakes anywhere. Thanks for any hints.

**Comment by Walleclipse** [comment]
Hi,
In general, `Hole Filling Filter` can smooth the image in real-time. `Denoising Filter` may much slower. If  `Hole Filling Filter`  is not running in your program, then I think it may have some bugs in code.

Please check the [example](https://github.com/intelligent-control-lab/Kinect_Smoothing/blob/master/example.ipynb), which smooth  Kinect camera depth images step by step.

**Comment by Cartucho** [comment]
Hi, I was testing this with my own image and it was getting stuck forever too.

I fixed it by commenting out the two following lines:
https://github.com/intelligent-control-lab/Kinect_Smoothing/blob/476110405635daab89777c76b9b849416e443d3b/kinect_smoothing/depth_image_smoothing.py#L113-L114

My guess is that if the min and max depth is not set correctly then everything is set to zero resulting on an infinite loop.
