### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by ShuangjunLiu** [intelligent-control-lab/Kinect_Smoothing#5]
After installing the requirements, I ran the kinect_preprocess_example.py and got error: 

> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "C:\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "C:\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "G:\My Drive\research\Sarah Ostadabbas\codePool\Kinect_Smoothing\kinect_preprocess_example.py", line 50, in kinect_preprocess
>     action, file_name = pose_path.split('/')[:-2]
> ValueError: not enough values to unpack (expected 2, got 0)
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "G:/My Drive/research/Sarah Ostadabbas/codePool/Kinect_Smoothing/kinect_preprocess_example.py", line 70, in <module>
>     kicet_preprocess_multi(data_dir, pose_save_dir, num_thread=8)
>   File "G:/My Drive/research/Sarah Ostadabbas/codePool/Kinect_Smoothing/kinect_preprocess_example.py", line 62, in kicet_preprocess_multi
>     pool.map(partial(kinect_preprocess,pose_save_dir=pose_save_dir),img_files)
>   File "C:\Anaconda3\lib\multiprocessing\pool.py", line 268, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "C:\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
>     raise self._value
> ValueError: not enough values to unpack (expected 2, got 0)

Process finished with exit code 1

OS: windows 10 
python: 3.7

**Comment by ShuangjunLiu** [comment]
It was also tested on centos7 python3.7 env with the same error.

**Comment by Walleclipse** [comment]
Hi,
The data-path is incorrect.
We provide the sample data in [data](https://github.com/intelligent-control-lab/Kinect_Smoothing/tree/master/data).
Please download the data and specify the path of the data at [line-66](https://github.com/intelligent-control-lab/Kinect_Smoothing/blob/6801c154a2fde59459d2a82cfbd8b5562d302f77/kinect_preprocess_example.py#L66) in `kinect_preprocess_example.py`.
`
data_dir = 'data/' # your data path
`
